# Generated by Django 4.1.3 on 2022-11-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='addr',
            field=models.CharField(default='addr', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='mobno',
            field=models.CharField(default='100000000', max_length=12),
        ),
    ]
