# Generated by Django 4.1.3 on 2022-11-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_currentorders_finishedorders_hotel_hotelowner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMate',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('timetoorder', models.IntegerField()),
                ('food', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='finishedorders',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='finishedorders',
            name='food',
        ),
        migrations.RemoveField(
            model_name='finishedorders',
            name='timetoorder',
        ),
        migrations.AddField(
            model_name='finishedorders',
            name='complients',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='finishedorders',
            name='review',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='finishedorders',
            name='email',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
